# Generated by Django 4.1.1 on 2025-04-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration_month',
            new_name='duration_months',
        ),
    ]
